### PR TITLE
Github Page

### LINKED ISSUE #57: Github page
Wrote a tentative page using http://github.com/rstacruz/flatdoc.

http://padi.github.io/light-service

Can't seem to make a pull request on a non-existing gh-pages branch

### PR DESCRIPTION
**Pull request by padi**
used https://github.com/rstacruz/flatdoc
resolves #57

### CODE REVIEW

**Comment by adomokos** [comment]
@padi: do we need this many commits? Yours is only the last 6.

**Comment by padi** [comment]
@adomokos Sorry, I just realized that I kept all of that history because I forked the repo (instead of downloading it). Will fix it later.

**Comment by adomokos** [comment]
No worries. Please fix it, I would like to merge this in!

**Comment by padi** [comment]
I forgot to add this in the first commit (that can't be rebased to edit): This started from SHA 9640e2e72d475e18b7b064f4c8d85df5490d63cd of rstacruz/flatdoc

Otherwise, this should be free of previous commits @adomokos

**Comment by adomokos** [comment]
@padi: It's been a while. Can we get this out?

**Comment by padi** [comment]
@adomokos I've repushed this. If you check the history, there's no other author anymore.

**Comment by adomokos** [comment]
Thank you for it! +1 :coffee:

**Pull request merged**
