### PR TITLE
0.8.0

### PR DESCRIPTION
**Pull request by adomokos**
Release candidate for LS Orchestrators.

### CODE REVIEW

**Comment by bwvoss** [comment]
I love the ability of orchestrators to push a specific amount of cyclomatic complexity to the highest, and most explicit level. 👍 When is the merge?

**Comment by adomokos** [comment]
I totally forgot the 0.7.0 release and just pushed it out last weekend. I'd like to give it 2 weeks before this is released. Feel free to use the 0.8.0 branch, it's a release candidate and treated as such.

**Comment by adomokos** [comment]
And please report back any issues you see. Thanks!

**Comment by padi** [comment]
:+1: Nice!

**Comment by bwvoss** [comment]
Wooooo!

**Pull request merged**
